### ISSUE TITLE
Checkboxes and radio buttons don't render under GTK 3.14

### ISSUE THREAD

**Issue by flexiondotorg** [snwh/yuyo-gtk-theme#13]
Hi Sam,

As discussed here is a reminder that Checkboxes and Radio buttons do not render under GTK 3.14 on Ubuntu MATE 15.04. This is most noticable in Ubiquity during the install where is not clear there is anything to be selected. The issue is also present in the installed system.

![yuyo-ubiquity-01](https://cloud.githubusercontent.com/assets/304639/5966478/921da2dc-a7fc-11e4-88e4-d939ff74174f.png)
![yuyo-ubiquity-02](https://cloud.githubusercontent.com/assets/304639/5966479/921e8c74-a7fc-11e4-9726-9d01088f2c79.png)

**Comment by snwh** [comment]
Hmm. I think I know what this issue it.

**Comment by snwh** [comment]
Possibly fixed, I'll need a confirmation by someone else.
