### ISSUE TITLE
Incomplete theming of text entry boxes

### ISSUE THREAD

**Issue by robsteady** [snwh/yuyo-gtk-theme#14]
![628d2ab097a2c5a5](https://cloud.githubusercontent.com/assets/3039367/6021026/4ec79452-ab80-11e4-9577-2764cacc5b53.png)
Notice the small edge of white around the entry box. Using Greybird as the comparison you can see how the entry box can look more polished. I believe this was an issue on both the light and dark themes.

**Comment by snwh** [comment]
I think this has been fixed in the latest round of commits.
