### ISSUE TITLE
Outward arrows in maximize button

### ISSUE THREAD

**Issue by tranjeeshan** [snwh/yuyo-gtk-theme#7]
Two outward arrows indicate 'maximize' when any window is small. That's feasible. When any window is in maximized state, the 'two outward pointing arrows' remain the same. This shouldn't be the case. While in maximized position, the arrows should point inward. Those should be inward pointing arrow in maximize position to indicate minimize. 
I don't know whether I've succeed making you understand my point. If you do, then consider this. It's legit :)

**Comment by snwh** [comment]
I think this depends on the window manager. The two alternatives you describe are the theme; I may have to change it if this is the case.

**Comment by snwh** [comment]
I've altered the window icon to better suit this.
